# Generated by Django 5.0.2 on 2024-03-01 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=1000, null=True)),
                ('national_id', models.ImageField(blank=True, null=True, upload_to='national_id_photo/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('employee_photo', models.ImageField(blank=True, null=True, upload_to='employee_photo/')),
                ('register_status', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
