# Generated by Django 5.0.2 on 2024-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_contactus_jobs_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_photo',
            field=models.ImageField(blank=True, null=True, upload_to='client_photos/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='national_id',
            field=models.ImageField(blank=True, null=True, upload_to='clients_national_id_photos/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(choices=[('quick_services', '????? ?????'), ('elderly_care', '????? ???? ????'), ('clinical_care', '??????? ????????'), ('disabled_care', '????? ??? ???????'), ('child_care', '????? ???????'), ('wound_care', '??????? ???????')], max_length=20),
        ),
    ]
