# Generated by Django 5.0.2 on 2024-03-05 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_alter_client_client_photo_alter_client_national_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(choices=[('quick_services', 'حالات طارئة'), ('elderly_care', 'رعاية الاطفال'), ('clinical_care', 'الرعاية السريرية'), ('disabled_care', 'رعاية المعاقين'), ('child_care', 'رعاية الطفل'), ('wound_care', 'رعاية المصابين')], max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
